      tailwind.config = {
        darkMode: "class",
        theme: {
          extend: {
            "colors": {
                    "surface-variant": "#e2e2e2",
                    "tertiary-container": "#5895ff",
                    "secondary-fixed": "#e4e2e1",
                    "on-surface": "#1a1c1c",
                    "on-primary": "#ffffff",
                    "on-primary-fixed-variant": "#7c2e00",
                    "on-primary-container": "#561d00",
                    "tertiary-fixed-dim": "#adc7ff",
                    "on-secondary-container": "#656464",
                    "background": "#f9f9f9",
                    "surface-container-low": "#f3f3f3",
                    "on-surface-variant": "#5a4136",
                    "surface-container-highest": "#e2e2e2",
                    "surface-dim": "#dadada",
                    "on-tertiary-fixed-variant": "#004493",
                    "tertiary": "#005bc0",
                    "surface-container-lowest": "#ffffff",
                    "surface": "#f9f9f9",
                    "on-error-container": "#93000a",
                    "tertiary-fixed": "#d8e2ff",
                    "inverse-on-surface": "#f1f1f1",
                    "primary": "#a33e00",
                    "on-tertiary": "#ffffff",
                    "error-container": "#ffdad6",
                    "secondary": "#5f5e5e",
                    "inverse-surface": "#2f3131",
                    "outline-variant": "#e3bfb1",
                    "on-tertiary-fixed": "#001a41",
                    "on-secondary-fixed-variant": "#474747",
                    "primary-container": "#ff6600",
                    "surface-container": "#eeeeee",
                    "on-background": "#1a1c1c",
                    "primary-fixed-dim": "#ffb596",
                    "on-secondary-fixed": "#1b1c1c",
                    "inverse-primary": "#ffb596",
                    "secondary-container": "#e4e2e1",
                    "on-error": "#ffffff",
                    "on-secondary": "#ffffff",
                    "surface-bright": "#f9f9f9",
                    "on-primary-fixed": "#360f00",
                    "outline": "#8e7164",
                    "primary-fixed": "#ffdbcd",
                    "surface-container-high": "#e8e8e8",
                    "on-tertiary-container": "#002d66",
                    "surface-tint": "#a33e00",
                    "error": "#ba1a1a",
                    "secondary-fixed-dim": "#c8c6c6"
            },
            "borderRadius": {
                    "DEFAULT": "0.125rem",
                    "lg": "0.25rem",
                    "xl": "0.5rem",
                    "full": "0.75rem"
            },
            "spacing": {
                    "stack-md": "16px",
                    "stack-lg": "32px",
                    "stack-sm": "4px",
                    "margin-mobile": "16px",
                    "gutter": "24px",
                    "base": "8px",
                    "container-max": "1280px",
                    "margin-desktop": "40px"
            },
            "fontFamily": {
                    "body-md": ["Inter"],
                    "display-lg": ["Hanken Grotesk"],
                    "label-tech": ["JetBrains Mono"],
                    "headline-md": ["Hanken Grotesk"],
                    "headline-lg": ["Hanken Grotesk"],
                    "headline-lg-mobile": ["Hanken Grotesk"],
                    "body-lg": ["Inter"]
            },
            "fontSize": {
                    "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
                    "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                    "label-tech": ["13px", {"lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "500"}],
                    "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
                    "headline-lg": ["32px", {"lineHeight": "1.2", "fontWeight": "600"}],
                    "headline-lg-mobile": ["28px", {"lineHeight": "1.2", "fontWeight": "600"}],
                    "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}]
            }
          },
        },
      }
